include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - sort_child_properties_last
    - avoid_dynamic_calls

analyzer:
  errors:
    cancel_subscriptions: error
    always_declare_return_types: error
    close_sinks: error
    sort_child_properties_last: error
    prefer_const_constructors: error
    always_require_non_null_named_parameters: error
    annotate_overrides: error
    avoid_function_literals_in_foreach_calls: error
    avoid_init_to_null: error
    avoid_null_checks_in_equality_operators: error
    avoid_renaming_method_parameters: error
    avoid_return_types_on_setters: error
    avoid_returning_null_for_void: error
    avoid_single_cascade_in_expression_statements: error
    constant_identifier_names: error
    control_flow_in_finally: error
    empty_constructor_bodies: error
    empty_statements: error
    exhaustive_cases: error
    implementation_imports: error
    library_names: error
    library_prefixes: error
    null_closures: error
    overridden_fields: error
    package_names: error
    prefer_adjacent_string_concatenation: error
    prefer_collection_literals: error
    prefer_conditional_assignment: error
    prefer_contains: error
    prefer_equal_for_default_values: error
    prefer_final_fields: error
    prefer_for_elements_to_map_fromIterable: error
    prefer_function_declarations_over_variables: error
    prefer_if_null_operators: error
    prefer_initializing_formals: error
    prefer_inlined_adds: error
    prefer_is_not_operator: error
    prefer_null_aware_operators: error
    prefer_spread_collections: error
    prefer_void_to_null: error
    recursive_getters: error
    slash_for_doc_comments: error
    type_init_formals: error
    unnecessary_brace_in_string_interps: error
    unnecessary_const: error
    unnecessary_getters_setters: error
    unnecessary_new: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_string_escapes: error
    unnecessary_string_interpolations: error
    unnecessary_this: error
    use_function_type_syntax_for_parameters: error
    use_rethrow_when_possible: error
    dead_code: error
    await_only_futures: error
    camel_case_types: error
    empty_catches: error
    avoid_dynamic_calls: error